- platform: uptime
  unit_of_measurement: days

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent
    - type: last_boot

##########################################################
## NAS
##########################################################

- platform: qnap
  host: 192.168.1.253
  port: 443
  username: !secret qnap_username
  password: !secret qnap_password
  ssl: true
  verify_ssl: false
  monitored_conditions:
    - status
    - memory_percent_used
    - system_temp
    - cpu_usage
    - drive_smart_status
    - volume_percentage_used

# - platform: rest
#   scan_interval: 86400
#   resource: https://api.ipify.org/
#   name: External IP
#   value_template: '{{ value }}'

#############################################################################################################
###  This part of the automation is hidden due to the External IP address being exposed  ##
# - platform: template
  # sensors:
    # ipchange:
      # entity_id: sensor.external_ip
      # value_template: "{%- if is_state('sensor.external_ip', 'xxx.xxx.xxx.xxx') -%} False {%- elif is_state('sensor.external_ip', 'unknown' ) -%} False {%- else -%} True {%- endif %}"
#############################################################################################################