#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Read all about this and more at https://vCloudInfo.com
# Additional Light groups control file for better Alexa / HomeKit support
# https://github.com/CCOSTAN/Home-AssistantConfig/issues/764
######################################################################################################

# # Reference : https://www.flexfireleds.com/pages/Comparison-between-3528-LEDs-and-5050-LEDs.html
# - platform: flux_led
#   automatic_add: True
#   devices:
#     192.168.10.30:
#       name: led_garage_snip
#       mode: "rgb"
#     192.168.10.31:
#       name: led_outdoor_den
#       mode: "rgb"
#     192.168.10.32:
#       name: led_garage_large
#       mode: "rgb"
#     192.168.10.33:
#       name: led_garage_small
#       mode: "rgb"

# - platform: group
#   name: Kitchen Lights
#   entities:
#     - light.k1
#     - light.k2
#     - light.k3
#     - light.k4
#     - light.k5
#     - light.k6
#     - light.sink
#     - light.fridge

# - platform: group
#   name: Bedroom lights
#   entities:
#     - light.bedroom

- platform: group
  name: Living Room lights
  entities:
    - light.m1_back_left
    - light.m1_back_right
    - light.m1_front_left
    - light.m1_front_right

- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_1
    - light.dining_2
    - light.dining_3
    - light.dining_4

